version: '3'

services:
  db:
    container_name: db
    image: postgres:16.1-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - one-folder
    ports:
      - 5432:5432

volumes:
  postgres-data:

networks:
  one-folder: