export * as authControllers from './auth.controller';
export * as categoryControllers from './category.controller';
export * as commentControllers from './comment.controller';
export * as folderAccessControllers from './folder-access.controller';
export * as folderControllers from './folder.controller';
export * as ratingControllers from './rating.controller';
export * as roleControllers from './role.controller';
export * as softwareControllers from './software.controller';
export * as userControllers from './user.controller';
